[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
description = "Ignore test API keys in test files"
path = "tests/"
regex = "sk-test.*|A{21}|wJalrXUtnFEMIK.*|DUMMY_ALPACA_KEY.*|DUMMY_SECRET.*"
