"""Backtesting engine for QuantChain trading strategies."""

from .engine import (
    BacktestEngine,
    BacktestConfig,
    BacktestResult,
    MetricsResult,
    ConfigurationError,
    DataValidationError,
    BacktestExecutionError,
    validate_ohlcv_data,
    filter_data_by_date_range,
    calculate_basic_statistics,
)

from .market_friction import (
    MarketFrictionSimulator,
    MarketFrictionConfig,
    CommissionModel,
    FlatCommission,
    PercentageCommission,
    TieredCommission,
    SlippageModel,
    FixedSlippage,
    VolumeImpactSlippage,
    BidAskSpreadSlippage,
    LatencyModel,
    FixedLatency,
    UniformRandomLatency,
    NormalRandomLatency,
    InvalidFrictionModel,
    InvalidParameter,
    FrictionCalculationError,
    CustomFrictionModel,
)

from .performance_metrics import (
    PerformanceMetrics,
    InsufficientDataError,
    InvalidFrequencyError,
    MissingColumnError,
    MetricsCalculationError,
    LibraryImportError,
)

from .langgraph_adapter import (
    LangGraphBacktestAdapter,
    AgentStrategy,
    AgentState,
    DeterministicLLMWrapper,
    ReasoningEntry,
    PositionManager,
    bar_to_agent_state,
    agent_state_to_signal,
    capture_reasoning,
    create_standard_trading_agent,
    AgentExecutionError,
    TimeoutError,
    StateValidationError,
    SignalConversionError,
    PositionError,
    DeterministicRuleError,
    ScenarioLoadError,
)

__all__ = [
    "BacktestEngine",
    "BacktestConfig",
    "BacktestResult",
    "MetricsResult",
    "ConfigurationError",
    "DataValidationError",
    "BacktestExecutionError",
    "validate_ohlcv_data",
    "filter_data_by_date_range",
    "calculate_basic_statistics",
    "MarketFrictionSimulator",
    "MarketFrictionConfig",
    "CommissionModel",
    "FlatCommission",
    "PercentageCommission",
    "TieredCommission",
    "SlippageModel",
    "FixedSlippage",
    "VolumeImpactSlippage",
    "BidAskSpreadSlippage",
    "LatencyModel",
    "FixedLatency",
    "UniformRandomLatency",
    "NormalRandomLatency",
    "InvalidFrictionModel",
    "InvalidParameter",
    "FrictionCalculationError",
    "CustomFrictionModel",
    "PerformanceMetrics",
    "InsufficientDataError",
    "InvalidFrequencyError",
    "MissingColumnError",
    "MetricsCalculationError",
    "LibraryImportError",
    "LangGraphBacktestAdapter",
    "AgentStrategy",
    "AgentState",
    "DeterministicLLMWrapper",
    "ReasoningEntry",
    "PositionManager",
    "bar_to_agent_state",
    "agent_state_to_signal",
    "capture_reasoning",
    "create_standard_trading_agent",
    "AgentExecutionError",
    "TimeoutError",
    "StateValidationError",
    "SignalConversionError",
    "PositionError",
    "DeterministicRuleError",
    "ScenarioLoadError",
]
