name: Test Setup Python
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Hello
        run: python --version
